# Use una imagen base de Python
FROM python:3.9

# Establecer el directorio de trabajo en la imagen
WORKDIR /app

# Instalar las dependencias de Python necesarias
RUN pip install Flask
RUN pip install redis
RUN pip install gunicorn

# Copiar los archivos necesarios al contenedor
COPY api_flask.py /app

# Exponer el puerto 5000
EXPOSE 5000

# Variable de entorno para mostrar prints en tiempo real
ENV PYTHONUNBUFFERED TRUE

# Ejecutar la aplicación cuando se inicie el contenedor
# Mediante gunicorn con 4 workers
CMD ["gunicorn", "-b", "0.0.0.0:5000", "-w", "1", "api_flask:app"]

